# -*- coding: utf-8 -*-
"""url_shortener.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17_Y06Sif8zJVypDuUI-0hvwqmflV7Fj8
"""

pip install pyshorteners

pip install pyperclip

import pyshorteners

url = input("Please Enter the URL : ")


def s_url(url):
    s = pyshorteners.Shortener()
    result=s.tinyurl.short(url)
    print("Short URL is : ",result)

s_url(url)